version: '3.3'

networks:
  web:
    external: true

services:
  app:
    image: docker.pkg.github.com/nathan13888/ipstat/api:latest
    container_name: ipstat
    restart: unless_stopped
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: 100M
        reservations:
          cpus: '1.00'
          memory: 20M
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
        #- "traefik.http.routers.ipstat-router.tls=true"
      - "traefik.http.routers.ipstat-router.rule=Host(`ip.wocrekcatta.ml`)"
      - "traefik.http.routers.ipstat-router.service=ipstat"
      - "traefik.http.services.ipstat.loadbalancer.server.port=3000"
